// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp1;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(DataBasee))]
    [Migration("20240405142127_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("WinFormsApp1.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<float?>("feels_like")
                        .HasColumnType("REAL");

                    b.Property<float?>("humidity")
                        .HasColumnType("REAL");

                    b.Property<float>("lat")
                        .HasColumnType("REAL");

                    b.Property<float>("lon")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("pressure")
                        .HasColumnType("REAL");

                    b.Property<float?>("speed")
                        .HasColumnType("REAL");

                    b.Property<float?>("temp")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            lat = 0f,
                            lon = 0f,
                            name = "Gorzow"
                        },
                        new
                        {
                            Id = 2,
                            lat = 0f,
                            lon = 0f,
                            name = "Krakow"
                        },
                        new
                        {
                            Id = 3,
                            lat = 0f,
                            lon = 0f,
                            name = "Gdansk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
